import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Contact Us | Order Customized Gifts & Frames | Kalangan',
    description: 'Contact Kalangan for customized wedding frames, nameplates, birthday gifts, and personalized handmade products. WhatsApp: +91 98332 91030. Pan India delivery available. Fast response guaranteed.',
    keywords: [
        'contact Kalangan',
        'order wedding frames online',
        'buy customized nameplates',
        'personalized gifts contact',
        'handmade gifts WhatsApp order',
        'custom frame inquiry',
        'bulk order wedding gifts',
        'personalized keychains order',
        'fridge magnets bulk order',
        'wedding return gifts contact',
        'birthday gift customization',
        'nameplate order online India',

        // Contact page specific long-tail
        'how to order customized wedding frames online',
        'WhatsApp number for handmade gifts India',
        'contact details for personalized nameplate',
        'how to place bulk order for wedding return gifts',
        'customer service handmade gifts India',
        'inquiry for customized photo frames',
        'get quote for personalized keychains',
        'contact for bulk fridge magnets order',
        'how to order personalized gifts online India',
        'WhatsApp order for wedding frames',
        'phone number for customized nameplates',
        'email for handmade gift orders',
        'contact handmade gift shop Mumbai',
        'how to customize wedding frames online',
        'inquiry for personalized birthday gifts',
        'bulk order contact for return gifts',
        'customized frames delivery inquiry',
        'Pan India delivery contact details',
        'how to order handmade keychains bulk',
        'contact for wedding return gifts Mumbai',
        'personalized gifts customer support India',
        'handmade gifts order WhatsApp number',
        'customized nameplate inquiry contact',
        'how to get personalized fridge magnets',
        'contact for custom photo frames India'
    ],
    openGraph: {
        title: 'Contact Kalangan | Order Handmade Wedding Frames & Personalized Gifts',
        description: 'Get in touch for customized wedding frames, nameplates, birthday gifts & more. WhatsApp support available. Pan India delivery.',
        type: 'website',
    },
};
