import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'About Us | Handmade Gifts & Customized Frames',
    description: 'कलांगण is a heartfelt handmade gifting brand specializing in wedding frames, nameplates, birthday gifts, customized frames, fridge magnets and keychains. Based in Mumbai, Maharashtra, serving Pan India with love.',
    alternates: {
        canonical: '/about',
    },
    keywords: [
        'about Kalangan',
        'Kalangan handmade gifts',
        'कलांगण',
        'हस्तनिर्मित उपहार ब्रांड',
        'handmade gift brand India',
        'customized gifts Mumbai',
        'personalized gifting company',
        'wedding frame makers',
        'nameplate manufacturers India',
        'handcrafted gifts Maharashtra',
        'artisan gift shop',
        'custom frame business',
        'personalized gift service',
        'handmade return gifts',
        'who makes handmade wedding frames in India',
        'best handmade gift brand Mumbai',
        'trusted customized frame seller India',
        'authentic handcrafted gifts Mumbai Maharashtra',
        'story behind Kalangan handmade gifts',
        'why choose handmade gifts over machine made',
        'benefits of personalized handcrafted gifts',
        'local artisan gift makers Mumbai',
        'handmade gift business in Maharashtra',
        'Indian handcrafted gift brands',
        'personalized gift company Pan India',
        'handmade wedding frame artisans India',
        'customized nameplate makers Mumbai',
        'best handcrafted gift service India',
        'quality handmade gifts Mumbai',
        'experienced personalized gift makers',
        'handmade gift brand with Pan India delivery',
        'Mumbai based handcrafted gift company',
        'artisan made personalized gifts India'
    ],
    openGraph: {
        title: 'About Kalangan | Premium Handmade Gifts & Customized Frames',
        description: 'Discover our story of creating heartfelt handmade wedding frames, nameplates, and personalized gifts. Handcrafted with love in Mumbai, Maharashtra.',
        type: 'website',
        url: 'https://kalanganhandmade.in/about',
        images: [
            {
                url: '/logo.png',
                width: 512,
                height: 512,
                alt: 'About Kalangan handmade gifts',
            },
        ],
    },
};
