import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Products | Wedding Frames, Nameplates & Customized Gifts',
    description: 'Shop handmade wedding frames, personalized nameplates, birthday gifts, customized photo frames, fridge magnets & keychains. Premium handcrafted gifts for all occasions. Order online with Pan India delivery.',
    keywords: [
        'buy wedding frames online',
        'customized wedding frame India',
        'nameplate online shopping',
        'personalized nameplate for home',
        'birthday gift shop online',
        'customized frames with photos',
        'fridge magnets buy online',
        'personalized keychains India',
        'handmade gifts online store',
        'custom photo frames India',
        'wedding return gift ideas',
        'anniversary gift frames',
        'engagement gift frames',
        'housewarming nameplate',
        'wooden nameplate designs',
        'acrylic nameplate online',
        'couple keychains personalized',
        'photo fridge magnets custom',
        'handcrafted birthday presents',
        'personalized gift shop India',

        // Product page specific long-tail
        'where to buy handmade wedding frames online',
        'best online shop for customized nameplates',
        'affordable personalized gifts India',
        'unique handmade birthday gift ideas online',
        'custom photo frames with name online India',
        'personalized fridge magnets for wedding favors',
        'handmade keychains for couples online shopping',
        'buy customized frames for anniversary online',
        'personalized nameplate for main door online',
        'handcrafted wedding gift frames online India',
        'best quality customized photo frames online',
        'unique personalized keychains online India',
        'handmade fridge magnets online shopping',
        'customized birthday frames with photos online',
        'wooden nameplate online shopping India',
        'personalized couple keychains buy online',
        'handmade return gifts online store',
        'custom wedding frames online delivery',
        'personalized gifts online India cash on delivery',
        'handcrafted nameplates online purchase',
        'buy personalized photo frames online India',
        'customized fridge magnets online shopping',
        'handmade birthday gifts online delivery',
        'personalized keychains online India free shipping',
        'wedding frames online shopping with price',
        'customized nameplate online India best price',
        'handmade gifts online India affordable',
        'personalized frames online shopping Mumbai',
        'custom keychains online bulk order',
        'handcrafted wedding return gifts online',
        'personalized fridge magnets online India',
        'customized photo frames online same day delivery'
    ],
    openGraph: {
        title: 'Shop Handmade Wedding Frames, Nameplates & Customized Gifts | Kalangan',
        description: 'Browse our collection of handmade wedding frames, personalized nameplates, birthday gifts, and customized keychains. Premium quality, Pan India delivery.',
        type: 'website',
    },
};
