import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Handmade Gifts Online | Wedding Frames, Nameplates & Customized Gifts',
    description: 'Shop Kalangan handmade gifts online: wedding frames, personalized nameplates, birthday gifts, customized photo frames, fridge magnets, keychains, return gifts and keepsakes with Pan India delivery.',
    alternates: {
        canonical: '/products',
    },
    keywords: [
        'buy wedding frames online',
        'customized wedding frame India',
        'nameplate online shopping',
        'personalized nameplate for home',
        'birthday gift shop online',
        'customized frames with photos',
        'fridge magnets buy online',
        'personalized keychains India',
        'handmade gifts online store',
        'handmade gifts online India',
        'handmade gifts India',
        'unique handmade gifts India',
        'customized gifts online India',
        'personalized gifts online India',
        'personalised gifts India',
        'custom handmade gifts',
        'personalized handmade gifts',
        'handmade wedding gifts India',
        'personalized wedding gifts India',
        'handmade return gifts India',
        'bulk return gifts India',
        'birthday gifts online India',
        'anniversary gifts online India',
        'housewarming gifts India',
        'custom photo frames India',
        'wedding return gift ideas',
        'anniversary gift frames',
        'engagement gift frames',
        'housewarming nameplate',
        'wooden nameplate designs',
        'acrylic nameplate online',
        'couple keychains personalized',
        'photo fridge magnets custom',
        'handcrafted birthday presents',
        'personalized gift shop India',

        // Product page specific long-tail
        'where to buy handmade wedding frames online',
        'best online shop for customized nameplates',
        'affordable personalized gifts India',
        'unique handmade birthday gift ideas online',
        'custom photo frames with name online India',
        'personalized fridge magnets for wedding favors',
        'handmade keychains for couples online shopping',
        'buy customized frames for anniversary online',
        'personalized nameplate for main door online',
        'handcrafted wedding gift frames online India',
        'best quality customized photo frames online',
        'unique personalized keychains online India',
        'handmade fridge magnets online shopping',
        'customized birthday frames with photos online',
        'wooden nameplate online shopping India',
        'personalized couple keychains buy online',
        'handmade return gifts online store',
        'custom wedding frames online delivery',
        'personalized gifts online India cash on delivery',
        'handcrafted nameplates online purchase',
        'buy personalized photo frames online India',
        'customized fridge magnets online shopping',
        'handmade birthday gifts online delivery',
        'personalized keychains online India free shipping',
        'wedding frames online shopping with price',
        'customized nameplate online India best price',
        'handmade gifts online India affordable',
        'personalized frames online shopping Mumbai',
        'custom keychains online bulk order',
        'handcrafted wedding return gifts online',
        'personalized fridge magnets online India',
        'customized photo frames online same day delivery'
    ],
    openGraph: {
        title: 'Shop Handmade Gifts, Wedding Frames & Customized Gifts | Kalangan',
        description: 'Browse handmade wedding frames, personalized nameplates, birthday gifts, customized keychains, fridge magnets and return gifts. Premium quality, Pan India delivery.',
        type: 'website',
        url: 'https://kalanganhandmade.in/products',
        images: [
            {
                url: '/logo.png',
                width: 512,
                height: 512,
                alt: 'Kalangan handmade gifts collection',
            },
        ],
    },
};
